grade:
  image: cr.yandex/crpkun66rq02t8mpkpa4/cpp-course
  only:
    - /^submits/.*$/
  script:
    - cd /opt/shad && PYTHONPATH=grader python3 -m grader
  artifacts:
    when: on_failure
    paths:
      - artifacts/
